// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
//import frc.robot.pixy.PixyI2C;
import io.github.pseudoresonance.pixy2api.*;
import io.github.pseudoresonance.pixy2api.links.*;


/**
 *
 */
public class PixySystem extends SubsystemBase {

    private final Pixy2 pixy;

    public PixySystem() {      
        this(new SPILink());
    }

    public PixySystem(Link link) {
        pixy = Pixy2.createInstance(link);
        pixy.init();
    }

    public Pixy2 getPixy() {
        return pixy;
    }

}

