// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.drive;

import edu.wpi.first.wpilibj2.command.CommandBase;
//import frc.robot.Constants;  //uncomment when adding something that requires the constants file.
//import frc.robot.Robot;
import frc.robot.Robot;
import frc.robot.Constants.Drive;
/**
 *
 */
public class AutoDriveForward extends CommandBase {

    private double start;
    private double current;
    private double target;
    private double distance;

    public AutoDriveForward(int distance) {
        addRequirements(Robot.driveSystem);
        this.distance = distance;
    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        start = Robot.driveSystem.getAverageDistance();
        target = Robot.driveSystem.getAngle();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        current = Robot.driveSystem.getAverageDistance();
        Robot.driveSystem.driveForward(Drive.StraightSpeed, target);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        if(current - start >= distance) {
            return true;
        } else {
            return false;
        }
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {
        Robot.driveSystem.arcadeDrive(0, 0, 0);
    }

}
