// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Constants;
//import frc.robot.Robot;
import frc.robot.Robot;

/**
 *
 */
public class AutoDriveForward extends CommandBase {

    private double target;

    public AutoDriveForward() {
        addRequirements(Robot.driveSystem);
    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        
        target = Robot.driveSystem.getAngle();
        
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {

        Robot.driveSystem.arcadeDrive(Constants.driveStraightSpeed, Constants.maxTurnRate, target);

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        return !Robot.oi.getAutoDriveForwardButton();
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {

        Robot.driveSystem.arcadeDrive(0, 0, 0);
    }

}
